### ISSUE TITLE
Listener for New Messages

### ISSUE THREAD

**Issue by mjmon** [michaelspiss/imap_client#26]
Hello and good day

I came across this package and was wondering if there's an existing listener for incoming Messages on this Package?
Maybe something like below

```
imapClient.onNewMessage((event) => {
 //do something
})
```
I was planning to trigger a local notification if there's a new message so I was looking for a listener 

Looking forward to your response.

Thank you

**Comment by michaelspiss** [comment]
Hi, this package is in need of a major rewrite which I wanted to do once dart officially supports data classes (it's now been three years since they proposed it). Due to time constraints on my end I had to leave it in the state it currently is - which sadly means that a listener for incoming messages is not supported yet.

**Comment by mjmon** [comment]
Thank for your reply. I'll close this one for now
